### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/kita-explorer#2]
- https://github.com/technologiestiftung/kita-explorer/network/alert/scraper/package-lock.json/tough-cookie/open
- https://github.com/technologiestiftung/kita-explorer/network/alert/scraper/package-lock.json/lodash/open
- https://github.com/technologiestiftung/kita-explorer/network/alert/scraper/package-lock.json/sshpk/open

**Comment by Esshahn** [comment]
closing
