### ISSUE TITLE
harvester

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/kita-explorer#5]
python

**Comment by sebastian-meier** [comment]
Either their needs to be a new harvester for https://kita-navigator.berlin.de/api/v1/kitas/umkreissuche?entfernung=50&seite=0&max=5000 and individual pages e.g. https://kita-navigator.berlin.de/einrichtungen/1457?input=&betb=10-2020&einfacheSuche=true&entfernung=50&seite=1&index=0

which would be interesting because when we run this every other day, we could track open slots for every kita...

OTHERWISE... close the whole thing down...

**Comment by Esshahn** [comment]
closing
